"""
Assembly Grapher GUI — main application window.

Layout (tkinter + tkinter.ttk, no external dependencies)
─────────────────────────────────────────────────────────

┌──────────────────────────────────────────────────────────────────────┐
│  Menu: File | Analysis | View | Help                                 │
├──────────────┬───────────────────────────┬───────────────────────────┤
│  LEFT PANEL  │   CENTRE PANEL (tabbed)   │   RIGHT PANEL             │
│  Assembly    │                           │   DFMA / DFS              │
│  Tree        │  [Graph] [Sequence] [BOM] │   Warning List            │
│              │                           │                           │
│  ┌────────┐  │  ┌─────────────────────┐  │  ┌─────────────────────┐  │
│  │ ASM001 │  │  │  Assembly Graph     │  │  │ ● ERROR   (7)       │  │
│  │ ├ P001 │  │  │  (networkx / canvas)│  │  │   DFS-001 F001...   │  │
│  │ ├ P002 │  │  │                     │  │  │   DFS-004 F006...   │  │
│  │ ├ P003 │  │  │  Nodes: parts       │  │  │ ● WARNING (14)      │  │
│  │ ├ P004 │  │  │  Edges: liaisons    │  │  │   DFA-007 ASM001... │  │
│  │ └ ...  │  │  │  Colour: severity   │  │  │ ● INFO    (2)       │  │
│  └────────┘  │  └─────────────────────┘  │  └─────────────────────┘  │
│              │                           │                           │
│  Fasteners   │  [Sequence tab]           │  Selected warning detail  │
│  ┌────────┐  │  ┌─────────────────────┐  │  ┌─────────────────────┐  │
│  │ F001 ✗ │  │  │ Step 1: Base Part   │  │  │ Rule: DFS-001       │  │
│  │ F002 ✓ │  │  │ Step 2: Subasm A    │  │  │ Part: F001          │  │
│  │ F003 ✗ │  │  │ Step 3: ...         │  │  │ Value: 5.0 mm       │  │
│  └────────┘  │  └─────────────────────┘  │  │ Threshold: 8.0 mm   │  │
│              │                           │  │ Suggestion: ...     │  │
│  [Run DFMA]  │  [BOM tab]                │  └─────────────────────┘  │
│  [Run Screw] │  ┌─────────────────────┐  │                           │
│              │  │ Item | Qty | Process │  │  [Export Report]          │
└──────────────┴──┴─────────────────────┴──┴───────────────────────────┘
│  Status bar: "Analysis complete — 7 errors, 14 warnings, 2 infos"    │
└──────────────────────────────────────────────────────────────────────┘

Panels
──────
LEFT:   AssemblyTreePanel     — hierarchical treeview of Assembly / Part nodes
                                and a separate FastenerList showing each
                                FastenerSpec with a pass/fail icon.

CENTRE: CentreNotebook        — three tabs:
          GraphTab             — canvas rendering the assembly liaison graph
                                 using networkx for layout, drawn with
                                 tkinter Canvas primitives.  Nodes are coloured
                                 by worst-severity warning on that part.
          SequenceTab          — ordered step list generated by topological
                                 sort of the assembly graph, with drag-to-
                                 reorder (future) and per-step cycle-time.
          BOMTab               — ttk.Treeview table: Item | Part No | Qty |
                                 Process | Material | Status.

RIGHT:  WarningPanel          — ttk.Treeview grouped by severity.
                                 Clicking a row highlights the corresponding
                                 node in the GraphTab and scrolls the
                                 AssemblyTreePanel.
        DetailPanel           — shows full Warning text, metric vs threshold,
                                 and suggestion for the selected warning.

BOTTOM: StatusBar             — summary string + progress bar during analysis.

Inter-panel communication uses a simple publish/subscribe EventBus so panels
stay loosely coupled.
"""

import tkinter as tk
from tkinter import ttk, filedialog, messagebox

from .panels.assembly_tree  import AssemblyTreePanel
from .panels.graph_tab      import GraphTab
from .panels.sequence_tab   import SequenceTab
from .panels.bom_tab        import BOMTab
from .panels.resources_tab  import ResourcesTab
from .panels.warning_panel  import WarningPanel
from .event_bus             import EventBus


class App(tk.Tk):
    """Root window — wires all panels together via EventBus."""

    def __init__(self) -> None:
        super().__init__()
        self.title("Assembly Grapher — DFMA & Sequence Planner")
        self.geometry("1280x800")
        self.minsize(960, 600)

        self.bus = EventBus()
        self._assembly  = None   # most recently loaded Assembly object
        self._fasteners = []     # most recently loaded fastener list
        self._plan      = None   # most recently computed AssemblyPlan

        self._build_menu()
        self._build_layout()
        self._build_status_bar()
        self._setup_handlers()

    # ── menu ────────────────────────────────────────────────────────────────

    def _build_menu(self) -> None:
        menubar = tk.Menu(self)

        file_menu = tk.Menu(menubar, tearoff=0)
        file_menu.add_command(label="Open Assembly…",    command=self._open_assembly)
        file_menu.add_command(label="Open Fasteners…",   command=self._open_fasteners)
        file_menu.add_separator()
        file_menu.add_command(label="Export Report…",    command=self._export_report)
        file_menu.add_separator()
        file_menu.add_command(label="Exit",              command=self.destroy)
        menubar.add_cascade(label="File", menu=file_menu)

        analysis_menu = tk.Menu(menubar, tearoff=0)
        analysis_menu.add_command(label="Run DFMA Analysis",  command=self._run_dfma)
        analysis_menu.add_command(label="Run Screw Check",    command=self._run_screw)
        analysis_menu.add_command(label="Generate Sequence",  command=self._gen_sequence)
        menubar.add_cascade(label="Analysis", menu=analysis_menu)

        view_menu = tk.Menu(menubar, tearoff=0)
        view_menu.add_command(label="Fit Graph to Window",    command=self._fit_graph)
        view_menu.add_command(label="Reset Layout",           command=self._reset_layout)
        menubar.add_cascade(label="View", menu=view_menu)

        self.config(menu=menubar)

    # ── main layout ─────────────────────────────────────────────────────────

    def _build_layout(self) -> None:
        # Top-level horizontal paned window (left | centre+right)
        outer = ttk.PanedWindow(self, orient=tk.HORIZONTAL)
        outer.pack(fill=tk.BOTH, expand=True)

        # ── LEFT ────────────────────────────────────────────────────────────
        left_frame = ttk.Frame(outer, width=240)
        outer.add(left_frame, weight=1)

        self.tree_panel = AssemblyTreePanel(left_frame, self.bus)
        self.tree_panel.pack(fill=tk.BOTH, expand=True)

        btn_frame = ttk.Frame(left_frame)
        btn_frame.pack(fill=tk.X, padx=4, pady=4)
        ttk.Button(btn_frame, text="Run DFMA",        command=self._run_dfma).pack(
            side=tk.LEFT, expand=True, fill=tk.X, padx=2)
        ttk.Button(btn_frame, text="Run Screw Check", command=self._run_screw).pack(
            side=tk.LEFT, expand=True, fill=tk.X, padx=2)

        # ── CENTRE ──────────────────────────────────────────────────────────
        centre_right = ttk.PanedWindow(outer, orient=tk.HORIZONTAL)
        outer.add(centre_right, weight=4)

        centre_frame = ttk.Frame(centre_right)
        centre_right.add(centre_frame, weight=3)

        self.notebook = ttk.Notebook(centre_frame)
        self.notebook.pack(fill=tk.BOTH, expand=True)

        self.graph_tab    = GraphTab(self.notebook, self.bus)
        self.sequence_tab = SequenceTab(self.notebook, self.bus)
        self.bom_tab      = BOMTab(self.notebook, self.bus)
        self.resources_tab = ResourcesTab(self.notebook, self.bus)

        self.notebook.add(self.graph_tab,    text="Assembly Graph")
        self.notebook.add(self.sequence_tab, text="Sequence")
        self.notebook.add(self.bom_tab,      text="BOM")
        self.notebook.add(self.resources_tab, text="Resources")

        # ── RIGHT ────────────────────────────────────────────────────────────
        right_frame = ttk.Frame(centre_right, width=300)
        centre_right.add(right_frame, weight=2)

        self.warning_panel = WarningPanel(right_frame, self.bus)
        self.warning_panel.pack(fill=tk.BOTH, expand=True)

    # ── status bar ───────────────────────────────────────────────────────────

    def _build_status_bar(self) -> None:
        bar = ttk.Frame(self, relief=tk.SUNKEN)
        bar.pack(side=tk.BOTTOM, fill=tk.X)
        self._status_var = tk.StringVar(value="Ready — open an assembly to begin.")
        ttk.Label(bar, textvariable=self._status_var, anchor=tk.W).pack(
            side=tk.LEFT, padx=6)

    def _set_status(self, msg: str) -> None:
        self._status_var.set(msg)

    # ── command handlers (stubs — wired to real logic in future) ─────────────

    def _open_assembly(self) -> None:
        path = filedialog.askopenfilename(
            title="Open Assembly",
            filetypes=[
                ("SolidWorks Assembly", "*.sldasm"),
                ("STEP File",           "*.step *.stp"),
                ("PLMXML",              "*.xml"),
                ("JSON BOM",            "*.json"),
                ("All files",           "*.*"),
            ],
        )
        if path:
            self.bus.publish("assembly_loaded", path)
            self._set_status(f"Loaded: {path}")

    def _open_fasteners(self) -> None:
        path = filedialog.askopenfilename(
            title="Open Fastener Definitions",
            filetypes=[("JSON", "*.json"), ("All files", "*.*")],
        )
        if path:
            self.bus.publish("fasteners_loaded", path)

    def _export_report(self) -> None:
        path = filedialog.asksaveasfilename(
            title="Export DFMA Report",
            defaultextension=".txt",
            filetypes=[("Text Report", "*.txt"), ("CSV", "*.csv"),
                       ("JSON", "*.json"), ("All files", "*.*")],
        )
        if path:
            self.bus.publish("export_report", path)

    def _run_dfma(self)      -> None: self.bus.publish("run_dfma",     None)
    def _run_screw(self)     -> None: self.bus.publish("run_screw",    None)
    def _gen_sequence(self)  -> None: self.bus.publish("gen_sequence", "Optimized (Simulated Annealing)")
    def _fit_graph(self)     -> None: self.bus.publish("fit_graph",    None)
    def _reset_layout(self)  -> None: self.bus.publish("reset_layout", None)

    # ── internal event handlers ───────────────────────────────────────────────

    def _setup_handlers(self) -> None:
        """Subscribe to events that require cross-panel coordination."""
        self.bus.subscribe("assembly_loaded",  self._handle_assembly_loaded)
        self.bus.subscribe("fasteners_loaded", self._handle_fasteners_loaded)
        self.bus.subscribe("run_dfma",         self._handle_run_dfma)
        self.bus.subscribe("run_screw",        self._handle_run_screw)
        self.bus.subscribe("gen_sequence",     self._handle_gen_sequence)
        self.bus.subscribe("run_resources",    self._handle_run_resources)

    def _handle_assembly_loaded(self, assembly) -> None:
        """Store assembly object (may be a path string from file dialog or Assembly)."""
        if hasattr(assembly, "all_parts"):
            self._assembly = assembly

    def _handle_fasteners_loaded(self, fasteners) -> None:
        if isinstance(fasteners, list):
            self._fasteners = fasteners
            self._publish_resources(fasteners)

    def _handle_run_dfma(self, _data) -> None:
        if self._assembly is None:
            return
        try:
            from dfma.analyzer import analyze
            result = analyze(self._assembly, fasteners=self._fasteners or None)
            self.bus.publish("warnings_updated", result)
            e = len(result.errors())
            w = len(result.warnings_only())
            i = len(result.infos())
            self._set_status(
                f"DFMA complete — {e} error(s), {w} warning(s), {i} info(s) | "
                f"DFA Index: {result.dfa_index:.1%}"
            )
        except Exception as exc:
            self._set_status(f"DFMA error: {exc}")

    def _handle_run_screw(self, _data) -> None:
        if not self._fasteners:
            self._set_status("No fasteners loaded — run 'Open Fasteners' first.")
            return
        try:
            from dfma.rules.screw_rules import check_fasteners
            warnings = check_fasteners(self._fasteners)
            # Merge into current warnings if assembly was already analysed
            self._set_status(f"Screw check: {len(warnings)} issue(s) found.")
        except Exception as exc:
            self._set_status(f"Screw check error: {exc}")

    def _handle_gen_sequence(self, algo: str) -> None:
        """
        Run assembly planning and publish plan_ready + sequence_ready.
        Uses graph_demo.build_planner() when the loaded assembly is the
        pneumatic valve demo; falls back to a generic planner otherwise.
        """
        if self._assembly is None:
            self._set_status("No assembly loaded — cannot generate sequence.")
            return
        try:
            self._set_status("Generating sequence…")
            self.update_idletasks()

            # Build planner
            # Try the graph_demo builder first (demo assembly)
            try:
                from graph_demo import build_planner
                planner = build_planner()
            except Exception:
                from assembly_graph import AssemblyPlanner
                planner = AssemblyPlanner.from_assembly(
                    self._assembly, base_part_id=self._assembly.all_parts()[0].id
                )

            # Choose SA iterations by algo selector
            sa_iter = 2000
            if isinstance(algo, str) and "kahn" in algo.lower():
                sa_iter = 0
            elif isinstance(algo, str) and "greedy" in algo.lower():
                sa_iter = 0

            plan = planner.plan(sa_iterations=sa_iter)
            self._plan = plan

            # Publish plan for graph tab
            self.bus.publish("plan_ready", plan)

            # Choose sequence to display
            if isinstance(algo, str) and "greedy" in algo.lower():
                seq_result = plan.greedy_sequence
            elif isinstance(algo, str) and "kahn" in algo.lower():
                seq_result = plan.top_sequences[0] if plan.top_sequences else plan.greedy_sequence
            else:
                seq_result = plan.optimized_sequence

            steps = plan.optimized_steps()

            self.bus.publish("sequence_ready", {
                "steps":        steps,
                "cost_summary": seq_result.summary(),
            })

            self._set_status(
                f"Sequence generated — {len(steps)} parts | "
                f"{len(plan.subassemblies)} subassembly group(s) | "
                f"cost={plan.optimized_sequence.total_cost:.2f}"
            )
        except Exception as exc:
            self._set_status(f"Sequence error: {exc}")

    def _handle_run_resources(self, _data) -> None:
        self._publish_resources(self._fasteners)

    def _publish_resources(self, fasteners: list) -> None:
        if not fasteners:
            return
        try:
            from dfma.rules.resource_calculator import calculate_resources
            resources = calculate_resources(fasteners)
            self.bus.publish("resources_updated", resources)
        except Exception as exc:
            self._set_status(f"Resource calc error: {exc}")


def run() -> None:
    app = App()
    app.mainloop()


if __name__ == "__main__":
    run()
