#!/usr/bin/env python3
"""A simple air-resistance optimizer for the Kipinä airframe.

    python3 aero/optimize.py airframe            # at its cruise speed
    python3 aero/optimize.py airframe --kmh 65   # at 65 km/h
    python3 aero/optimize.py airframe --fix span,aspect_ratio

A model in aero/models/ turns a set of design parameters into a drag
build-up (aero/dragkit.py) and a list of broken limits. The optimizer then:

  1. ranks the single changes: each parameter alone, moved to its best allowed
     value, with everything else as built;
  2. searches all free parameters together (coordinate search on each
     parameter's grid, with shrinking steps) for the lowest drag at the speed.

It writes aero/REPORT_<model>.md and prints a summary.
"""
from __future__ import annotations

import argparse
import importlib
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

from dragkit import total  # noqa: E402
from model import Param, Result  # noqa: E402


# a move must save at least this fraction of the drag; smaller gains are within
# the model's noise and would only clutter the result
MIN_GAIN = 3e-4


def better(r: Result, best: Result) -> bool:
    return r.ok and r.drag < best.drag * (1 - MIN_GAIN)


class Counter:
    def __init__(self, model, v):
        self.model, self.v, self.n = model, v, 0

    def __call__(self, x: dict) -> Result:
        self.n += 1
        return self.model.evaluate(x, self.v)


def single_changes(ev, params: list[Param], x0: dict, free: list[str], base: Result):
    """Each free parameter alone over its whole grid; the best allowed value."""
    rows = []
    for p in params:
        if p.name not in free:
            continue
        n = int(round((p.hi - p.lo) / p.step))
        stride = max(1, n // 200)
        best_v, best = x0[p.name], base
        for i in range(0, n + 1, stride):
            v = p.snap(p.lo + i * p.step)
            r = ev({**x0, p.name: v})
            if better(r, best):
                best_v, best = v, r
        rows.append((p, best_v, best))
    rows.sort(key=lambda row: row[2].drag)
    return rows


def search(ev, params: list[Param], x0: dict, free: list[str], base: Result):
    """Coordinate search: try one grid move up and down on each parameter, keep
    any move that lowers the drag without breaking a limit; repeat until nothing
    helps, then halve the move and go again."""
    by_name = {p.name: p for p in params}
    x, best = dict(x0), base
    for mult in (16, 8, 4, 2, 1):
        improved = True
        while improved:
            improved = False
            for name in free:
                p = by_name[name]
                for sgn in (1, -1):
                    v = p.snap(x[name] + sgn * mult * p.step)
                    if v == x[name]:
                        continue
                    r = ev({**x, name: v})
                    if better(r, best):
                        x, best, improved = {**x, name: v}, r, True
    return x, best


def pct(a: float, b: float) -> str:
    return f"{(b - a) / a * 100:+.1f} %"


def write_report(model, params, free, v, x0, base, x1, best, singles, n_eval, out: Path):
    unit, scale = model.AREA_UNIT
    fmt = model.force_text
    L = [f"# Drag optimizer: {model.TITLE}", "",
         f"Generated by `aero/optimize.py {model.NAME}`. Do not edit by hand.", "",
         f"Speed: **{model.speed_text(v)}**. {len(free)} of {len(params)} parameters free, "
         f"{n_eval} drag evaluations. {model.NOTE}", "",
         "## Result", "",
         "| | as built | optimised | change |", "|---|---|---|---|",
         f"| Drag | {fmt(base.drag)} | **{fmt(best.drag)}** | {pct(base.drag, best.drag)} |",
         f"| Parasite drag area CdA | {total(base.items) * scale:.2f} {unit} | "
         f"{total(best.items) * scale:.2f} {unit} | {pct(total(base.items), total(best.items))} |"]
    for (label, a), (_, b) in zip(base.other, best.other):
        L.append(f"| {label} | {fmt(a)} | {fmt(b)} | {pct(a, b) if a else ''} |")
    for (label, a), (_, b) in zip(base.metrics, best.metrics):
        L.append(f"| {label} | {a} | {b} | |")
    L += ["", "## Changes in the optimum", "",
          "| parameter | as built | optimised | what it is | in the CAD model? |", "|---|---|---|---|---|"]
    for p in params:
        if p.name in free and x1[p.name] != x0[p.name]:
            L.append(f"| `{p.name}` | {p.show(x0[p.name])} | **{p.show(x1[p.name])}** | {p.what} | "
                     f"{'yes' if p.in_cad else 'no, a what-if'} |")
    if all(x1[p.name] == x0[p.name] for p in params):
        L.append("| (none) | | | the design as built is already the optimum | |")
    L += ["", "## One change at a time", "",
          "Each parameter alone, moved to its best allowed value, everything else as built. "
          "The savings do not simply add up: the combined optimum is above.", "",
          "| change | from | to | drag | saved |", "|---|---|---|---|---|"]
    for p, bv, r in singles:
        if bv == x0[p.name]:
            continue
        L.append(f"| {p.what} | {p.show(x0[p.name])} | {p.show(bv)} | {fmt(r.drag)} | "
                 f"{pct(base.drag, r.drag)} |")
    kept = [p for p, bv, _ in singles if bv == x0[p.name]]
    if kept:
        L += ["", f"No single move of these saves {MIN_GAIN * 100:.2f} % or more: " +
              ", ".join(f"`{p.name}` ({p.show(x0[p.name])})" for p in kept) + "."]
    L += ["", "## Drag build-up", "",
          f"| item | as built, {unit} | share | optimised, {unit} | note |", "|---|---|---|---|---|"]
    t0 = total(base.items)
    after = {i.name: i.cda for i in best.items}
    for i in base.items:
        L.append(f"| {i.name} | {i.cda * scale:.2f} | {i.cda / t0 * 100:.0f} % | "
                 f"{after.get(i.name, 0) * scale:.2f} | {i.note} |")
    for i in best.items:
        if i.name not in {b.name for b in base.items}:
            L.append(f"| {i.name} | - | - | {i.cda * scale:.2f} | {i.note} |")
    L += ["", "## Parameters and limits", "",
          "| parameter | range | step | limit | free |", "|---|---|---|---|---|"]
    for p in params:
        L.append(f"| `{p.name}` | {p.show(p.lo)} to {p.show(p.hi)} | {p.show(p.step) if not p.labels else '-'} | "
                 f"{p.limit or '-'} | {'yes' if p.name in free else 'fixed'} |")
    L += ["", "## Method and limits", "", model.METHOD.strip(), ""]
    out.write_text("\n".join(L))


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("model", help="a model in aero/models/, e.g. airframe")
    ap.add_argument("--speed", type=float, help="speed in m/s (default: the model's own)")
    ap.add_argument("--kmh", type=float, help="speed in km/h")
    ap.add_argument("--fix", default="", help="comma-separated parameters to keep as built")
    ap.add_argument("--only", default="", help="comma-separated parameters to free (all others fixed)")
    ap.add_argument("--out", help="report path (default aero/REPORT_<model>.md)")
    a = ap.parse_args(argv)

    available = sorted(f.stem for f in (HERE / "models").glob("*.py") if not f.stem.startswith("_"))
    if a.model not in available:
        ap.error(f"no model {a.model!r}; available: {', '.join(available)}")
    model = importlib.import_module(f"models.{a.model}")
    v = a.speed or (a.kmh / 3.6 if a.kmh else model.SPEED)
    params = model.params()
    names = [p.name for p in params]
    fix = {s for s in a.fix.split(",") if s}
    only = {s for s in a.only.split(",") if s}
    for s in fix | only:
        if s not in names:
            ap.error(f"unknown parameter {s!r}; {a.model} has {', '.join(names)}")
    free = [n for n in names if n not in fix and (not only or n in only)]

    ev = Counter(model, v)
    x0 = {p.name: p.value for p in params}
    base = ev(x0)
    if not base.ok:
        sys.exit(f"the design as built breaks a limit: {'; '.join(base.violations)}")
    singles = single_changes(ev, params, x0, free, base)
    x1, best = search(ev, params, x0, free, base)
    # the search is local; if a single change beat it, start again from there
    for p, bv, r in singles:
        if better(r, best):
            x1, best = search(ev, params, {**x0, p.name: bv}, free, r)

    out = Path(a.out) if a.out else HERE / f"REPORT_{a.model}.md"
    write_report(model, params, free, v, x0, base, x1, best, singles, ev.n, out)

    fmt = model.force_text
    print(f"{model.TITLE} at {model.speed_text(v)}: drag {fmt(base.drag)} -> {fmt(best.drag)} "
          f"({pct(base.drag, best.drag)}), {ev.n} evaluations")
    by_name = {p.name: p for p in params}
    for n in free:
        if x1[n] != x0[n]:
            print(f"  {n:16s} {by_name[n].show(x0[n]):>12s} -> {by_name[n].show(x1[n])}")
    try:
        shown = out.relative_to(Path.cwd())
    except ValueError:
        shown = out
    print(f"wrote {shown}")


if __name__ == "__main__":
    main()
