#pragma once

#include <array>
#include <vector>

#include "voxel_map.hpp"
#include "voxel_planner.hpp"

// ---------------------------------------------------------------------------
// TRAJECTORY LIBRARY planner -- the thing the reactive layer should have been.
//
// WHY THIS REPLACES A DIRECTION HISTOGRAM. GeneralPlanner answers "which
// bearing looks most open" and hands that to a vehicle that needs 0.35 s to
// turn. The bearing is not a thing the aircraft can do; it is a wish. Every
// steering fix in this project -- commitment, hysteresis, the dwell margin, the
// reference-bearing low-pass -- exists to paper over that mismatch. A
// trajectory library removes the mismatch instead: every candidate is a path
// the airframe can actually fly, because it was generated by integrating the
// airframe's own model.
//
// AND IT IS CHEAPER. Measured on the same map:
//
//     openness field   96 az x 9 el x (64 march + 37 swept x 57 cells) = 1.88 M
//                      lookups, 4.52 ms
//     this, 200 prims  200 x 20 pts x 57 cells = 0.23 M lookups, ~0.55 ms
//
// Which stops being surprising once stated: the histogram ray-marches 864
// directions and throws away 863 of them. A library evaluates a few hundred
// specific paths and keeps the best one whole.
//
// PRIMITIVES ARE PRECOMPUTED IN THE BODY FRAME and rotated by the current
// heading at runtime. That is the whole reason this is affordable -- the
// rollout integration happens once at construction, not per step.
//
// SAFETY IS UNCHANGED IN KIND. A candidate is admissible only if the swept
// robot volume along it is clear in the CURRENT map, and commanded speed is
// still a stopping-distance budget against confirmed-free distance. Unknown
// space still earns no speed. What changes is the shape of what gets checked,
// not the standard it is held to.
// ---------------------------------------------------------------------------

namespace sim {

struct TrajParams {
    // Library shape. nYaw x nClimb x nSpeed primitives. 13 x 5 x 3 = 195, which
    // costs about 0.55 ms -- an eighth of the budget the histogram used.
    int   nYaw       = 13;
    int   nClimb     = 5;
    int   nSpeed     = 3;
    float maxYawRate = 100.f;   // deg/s at the extremes of the fan
    float maxClimb   = 1.5f;    // m/s
    float horizonS   = 2.0f;    // rollout length in TIME, not distance, so that
                                // slow primitives are short and fast ones long
                                // -- which is what makes the speed choice
                                // honest rather than cosmetic
    float dt         = 0.1f;    // rollout step; matches the control period
    // MUST MATCH THE VEHICLE. If this lags differently from the thing actually
    // being flown, every primitive is a lie and the planner is choosing between
    // fictions. Kept as a parameter rather than a constant precisely so it can
    // be set from the same place the simulator gets it.
    float tau        = 0.35f;
    float vMax       = 3.0f;
    float robotR     = 0.6f;
    float decelMs2   = 3.0f;
    float reactS     = 0.25f;
    float minFreeM   = 0.4f;
    // THE VOLUME YOU ARE ABOUT TO OCCUPY MUST BE POSITIVELY KNOWN CLEAR, not
    // merely "not known to be blocked". This is the fix for the failure that
    // an invisible trunk is UNKNOWN rather than OCCUPIED: measured at the
    // collision, all 5 truth-solid cells inside the robot volume were UNKNOWN,
    // and the old test -- which rejected only OCCUPIED -- waved them through.
    //
    // Requiring the WHOLE swept ball to be FREE deadlocks: with a forward
    // camera the sides and rear are permanently unknown, and this project has
    // already spent 638 of 700 steps stationary learning that. So the idea was
    // to split it -- CORE confirmed free, outer margin merely unoccupied.
    //
    // IT DOES NOT WORK, AND IS OFF BY DEFAULT. Swept against trunk visibility,
    // 400 steps, 4 seeds:
    //
    //     trunkTex  coreFrac   coll/4  travel  endDist  stopped
    //     0.70      0.00         0/4     68.3    107.9      169
    //     0.70      0.65         0/4     53.9    122.4      217
    //     0.25      0.00         0/4     56.1    120.6      210
    //     0.25      0.65         1/4     36.9    139.5      180
    //     0.15      0.00         4/4      6.9    169.1        0
    //     0.15      0.65         4/4     57.9    118.9        1
    //
    // Never safer, usually slower. At 0.25 it is the arm that collides while
    // the arm without it does not -- one run of four, so not significant, but
    // certainly no evidence for it. At 0.15 both fail totally; coreFrac only
    // delays the crash, which is cosmetic.
    //
    // The reasoning behind it still looks right: unknown space inside your own
    // body's volume is exactly where an unmatched obstacle hides. The
    // measurement disagrees, and the measurement wins. Kept behind --corefrac
    // with the numbers attached, because the next person will think of it too.
    //
    // Intermediate values were NOT tested; only 0 and 0.65.
    float coreFrac   = 0.0f;    // 1.0 = whole ball must be FREE, 0 = off
    // How far along the winning rollout to aim. This is NOT a free parameter:
    // commanding a straight bearing to a point on a curved path flies a CHORD,
    // and the chord bows inside the tube that was collision-checked by
    // R(1-cos(theta/2)). At 100 deg/s that is 0.10 m at 0.4 s and 0.026 m at
    // 0.2 s. Measured: aiming at 0.4 s cost 0.17 m of minimum true clearance
    // against the histogram planner. Short is safe; too short and the command
    // is dominated by the first-order lag rather than the plan.
    float aimS       = 0.2f;

    // Scoring. Deliberately few terms: this project has already measured that
    // adding weights to a badly-posed problem does not fix it.
    float goalWeight   = 1.0f;   // alignment of the endpoint with the goal bearing
    float clearWeight  = 0.7f;   // how far along the primitive stays clear
    float smoothWeight = 0.25f;  // prefer low yaw rate, all else equal
};

class TrajectoryPlanner {
public:
    explicit TrajectoryPlanner(const TrajParams& p = TrajParams());
    const TrajParams& params() const { return p_; }

    // Same signature and same return type as GeneralPlanner::plan, so the two
    // can be swapped behind one flag and compared on identical worlds. The
    // extra argument is the vehicle's current heading, which a body-frame
    // library needs and a world-frame histogram did not.
    GeneralResult plan(const VoxelMap& m, float px, float py, float pz,
                       float curYawDeg, float goalAzDeg, float goalElDeg);

    // The winning rollout in WORLD coordinates, for drawing. Empty if blocked.
    const std::vector<std::array<float, 3>>& chosen() const { return chosen_; }
    // Every admissible candidate, world frame -- this is the picture that makes
    // a bad decision obvious, because you can see what it rejected.
    const std::vector<std::vector<std::array<float, 3>>>& candidates() const {
        return cands_;
    }
    size_t librarySize() const { return prims_.size(); }

private:
    struct Prim {
        std::vector<std::array<float, 3>> pts;  // body frame, +y forward
        float speed = 0, yawRate = 0, climb = 0;
    };
    TrajParams p_;
    std::vector<Prim> prims_;
    std::vector<std::array<float, 3>> chosen_;
    std::vector<std::vector<std::array<float, 3>>> cands_;
    float lastAz_ = 0, lastEl_ = 0;
    bool  haveLast_ = false;
};

}  // namespace sim
