#pragma once

#include <array>
#include <vector>

#include "voxel_map.hpp"
#include "bearing_field.hpp"
#include "voxel_planner.hpp"

// ---------------------------------------------------------------------------
// TRAJECTORY LIBRARY planner -- the thing the reactive layer should have been.
//
// WHY THIS REPLACES A DIRECTION HISTOGRAM. GeneralPlanner answers "which
// bearing looks most open" and hands that to a vehicle that needs 0.35 s to
// turn. The bearing is not a thing the aircraft can do; it is a wish. Every
// steering fix in this project -- commitment, hysteresis, the dwell margin, the
// reference-bearing low-pass -- exists to paper over that mismatch. A
// trajectory library removes the mismatch instead: every candidate is a path
// the airframe can actually fly, because it was generated by integrating the
// airframe's own model.
//
// AND IT IS CHEAPER. Measured on the same map:
//
//     openness field   96 az x 9 el x (64 march + 37 swept x 57 cells) = 1.88 M
//                      lookups, 4.52 ms
//     this, 200 prims  200 x 20 pts x 57 cells = 0.23 M lookups, ~0.55 ms
//
// Which stops being surprising once stated: the histogram ray-marches 864
// directions and throws away 863 of them. A library evaluates a few hundred
// specific paths and keeps the best one whole.
//
// PRIMITIVES ARE PRECOMPUTED IN THE BODY FRAME and rotated by the current
// heading at runtime. That is the whole reason this is affordable -- the
// rollout integration happens once at construction, not per step.
//
// SAFETY IS UNCHANGED IN KIND. A candidate is admissible only if the swept
// robot volume along it is clear in the CURRENT map, and commanded speed is
// still a stopping-distance budget against confirmed-free distance. Unknown
// space still earns no speed. What changes is the shape of what gets checked,
// not the standard it is held to.
// ---------------------------------------------------------------------------

namespace sim {

struct TrajParams {
    // Library shape. nYaw x nClimb x nSpeed primitives. 13 x 5 x 3 = 195, which
    // costs about 0.55 ms -- an eighth of the budget the histogram used.
    int   nYaw       = 13;
    int   nClimb     = 5;
    int   nSpeed     = 3;
    float maxYawRate = 100.f;   // deg/s at the extremes of the fan
    float maxClimb   = 1.5f;    // m/s
    float horizonS   = 2.0f;    // rollout length in TIME, not distance, so that
                                // slow primitives are short and fast ones long
                                // -- which is what makes the speed choice
                                // honest rather than cosmetic
    float dt         = 0.1f;    // rollout step; matches the control period
    // MUST MATCH THE VEHICLE. If this lags differently from the thing actually
    // being flown, every primitive is a lie and the planner is choosing between
    // fictions. Kept as a parameter rather than a constant precisely so it can
    // be set from the same place the simulator gets it.
    float tau        = 0.35f;
    float vMax       = 3.0f;
    float robotR     = 0.6f;
    float decelMs2   = 3.0f;
    float reactS     = 0.25f;
    float minFreeM   = 0.4f;
    // HOW MUCH OF THE CONFIRMED-FREE RUN IS GIVEN BACK AS MARGIN.
    //
    // `sphereClear` already proved a ball of radius robotR is clear at EVERY
    // rollout point, so `bestFree` is the distance the CENTRE may travel with
    // the body clear -- it is already body-inclusive. The original code then
    // subtracted robotR from it again, which charges the airframe twice and
    // makes the bar to move at all `bestFree > robotR + minFreeM` = 1.0 m at
    // the defaults. Measured `bestFree` when stopped in a forest: 0.54 m.
    //
    // 1.0 = the original double-charge, 0.0 = trust the sphere test. Swept
    // against TRUE clearance, not just progress, because the margin is only
    // worth keeping if removing it costs safety.
    float freeMarginFrac = 1.0f;
    // THE VOLUME YOU ARE ABOUT TO OCCUPY MUST BE POSITIVELY KNOWN CLEAR, not
    // merely "not known to be blocked". This is the fix for the failure that
    // an invisible trunk is UNKNOWN rather than OCCUPIED: measured at the
    // collision, all 5 truth-solid cells inside the robot volume were UNKNOWN,
    // and the old test -- which rejected only OCCUPIED -- waved them through.
    //
    // Requiring the WHOLE swept ball to be FREE deadlocks: with a forward
    // camera the sides and rear are permanently unknown, and this project has
    // already spent 638 of 700 steps stationary learning that. So the idea was
    // to split it -- CORE confirmed free, outer margin merely unoccupied.
    //
    // IT DOES NOT WORK, AND IS OFF BY DEFAULT. Swept against trunk visibility,
    // 400 steps, 4 seeds:
    //
    //     trunkTex  coreFrac   coll/4  travel  endDist  stopped
    //     0.70      0.00         0/4     68.3    107.9      169
    //     0.70      0.65         0/4     53.9    122.4      217
    //     0.25      0.00         0/4     56.1    120.6      210
    //     0.25      0.65         1/4     36.9    139.5      180
    //     0.15      0.00         4/4      6.9    169.1        0
    //     0.15      0.65         4/4     57.9    118.9        1
    //
    // Never safer, usually slower. At 0.25 it is the arm that collides while
    // the arm without it does not -- one run of four, so not significant, but
    // certainly no evidence for it. At 0.15 both fail totally; coreFrac only
    // delays the crash, which is cosmetic.
    //
    // The reasoning behind it still looks right: unknown space inside your own
    // body's volume is exactly where an unmatched obstacle hides. The
    // measurement disagrees, and the measurement wins. Kept behind --corefrac
    // with the numbers attached, because the next person will think of it too.
    //
    // Intermediate values were NOT tested; only 0 and 0.65.
    float coreFrac   = 0.0f;    // 1.0 = whole ball must be FREE, 0 = off
    // How far along the winning rollout to aim. This is NOT a free parameter:
    // commanding a straight bearing to a point on a curved path flies a CHORD,
    // and the chord bows inside the tube that was collision-checked by
    // R(1-cos(theta/2)). At 100 deg/s that is 0.10 m at 0.4 s and 0.026 m at
    // 0.2 s. Measured: aiming at 0.4 s cost 0.17 m of minimum true clearance
    // against the histogram planner. Short is safe; too short and the command
    // is dominated by the first-order lag rather than the plan.
    float aimS       = 0.2f;
    // ROLLOUT CAP -- stop evaluating a primitive past this many metres.
    //
    // WARNING: THIS DOES NOT SUBSTITUTE FOR CHANGING `horizonS`, and the first
    // version of this comment claimed it did. Measured, 6 seeds, indoor:
    //
    //     --horizon 1.2  (3.6 m primitives)   travel 12.0 m   progress 34.3 %
    //     --rollcap 3.6  (6 m primitives)     travel  5.4 m   progress 15.5 %
    //     --rollcap off                       travel  5.4 m   progress 15.4 %
    //
    // The cap changes NOTHING indoors and only hurts in the forest. Why: a
    // shorter horizon changes the primitive LIBRARY and, decisively, the
    // scoring normaliser -- `clear = freeLen / (vMax * horizonS)`. Shrink the
    // denominator and a given free length scores far higher, so a DIFFERENT
    // primitive wins. Truncating the walk leaves the denominator, the primitive
    // shape and the aim point untouched, so the same primitive still wins; it
    // just knows less about it.
    //
    // The real fix is to hold two or three precomputed libraries at different
    // horizons (about 50 kB each) and select one, not to truncate one library.
    //
    // It matters because the right rollout length is a property of the ROOM,
    // not of the aircraft, and the two environments measured want opposite
    // values. 6 seeds each, trajectory planner:
    //
    //     rollout   forest (dist to goal)   indoor (progress %)
    //     1.5 m           --                     10.8
    //     2.4 m         185.7                    25.3
    //     3.6 m         181.2                    34.3   <- indoor best
    //     6.0 m         158.1  <- forest best    15.4
    //     9.0 m         172.8                    13.7
    //
    // A 6 m tube cannot exist in a 6 m room, and 207 of 210 primitives were
    // rejected on MAPPED walls with freeM collapsing to 0.15 m. Cap it at what
    // the surroundings actually offer and the same planner moves 2.2x further.
    //
    // <= 0 disables (evaluate the whole rollout, the original behaviour).
    float rollCapM   = 0.f;
    // ESCAPE PRIMITIVES -- lateral and rearward translation at the current
    // heading. A multirotor is holonomic; the arc primitives above are a CAR
    // model, and every one of them begins by moving forward.
    //
    // Measured in the cul-de-sac: pressed 0.31 m from the closed wall, the
    // aircraft sat at 0.00 m/s for 200 steps. Not because it chose to -- because
    // no primitive in the library retreated, so the best available free run was
    // under a metre and the speed budget correctly commanded zero. It had no
    // way out to choose.
    //
    // These keep the camera pointing where it was, which is the safe direction
    // to retreat in: the space behind the aircraft is the space it just flew
    // through, so it is mapped. Speed is reduced because flying somewhere the
    // camera is not looking should be deliberate and slow.
    int   nEscape    = 8;        // rearward/lateral directions; 0 disables
    float escapeSpeed= 1.0f;     // m/s
    float escapeMinDeg = 60.f;   // only directions at least this far off nose

    // LATERAL VELOCITY COUPLED TO YAW RATE -- the forward arcs are still a car
    // model even though the aircraft is not a car.
    //
    // DeFoP (arXiv 2512.17553) sets v_y = arctan(yaw command): while turning, a
    // multirotor also translates sideways, so the velocity vector LEADS the
    // heading instead of waiting for it. That is the manoeuvre a quad actually
    // performs to step around a trunk, and no arc in this library can express
    // it -- every one of them begins by moving straight ahead and only displaces
    // laterally as the integrated heading comes round. The escape set already
    // exploits holonomy, but only for retreat.
    //
    // IMPLEMENTED AS A SIDESLIP ANGLE, NOT AS AN ADDED VELOCITY, and the
    // difference is a safety property rather than a preference. DeFoP's literal
    // form adds a lateral component, which raises ground speed to
    // sqrt(v^2 + v_y^2) -- above the speed the primitive was scored and
    // stopping-distance budgeted at. Rotating the velocity vector by beta
    // instead keeps |v| exactly equal to the primitive's speed, so the one
    // invariant this planner has (never command faster than you can stop inside
    // what you have confirmed free) is untouched, and the whole change is
    // expressible as where the rollout points land.
    //
    //     beta = latSlipDeg * (2/pi) * arctan(yawRate / latKneeDps)
    //
    // Continuous and saturating, exactly as in the paper -- not discretised into
    // a few lateral primitives, which would multiply the library size for a
    // parameter that is naturally smooth.
    //
    // SIM CAVEAT, stated because it bounds what the A/B can show: voxel_sim
    // slaves heading to course (yaw = atan2(vx, vy)), so the modelled vehicle
    // has no sideslip of its own. What this measures there is the SHAPE of the
    // primitives -- turning candidates displace laterally sooner, so different
    // paths become admissible. The other half of the benefit, keeping the camera
    // pointed where it was while the body slides, cannot be measured until the
    // simulated vehicle gets a yaw model independent of its velocity.
    //
    // AND IT IS "SOONER", NOT "WIDER" -- test/sideslip_check.cpp measures this.
    // At 20 deg and 100 deg/s the lateral offset roughly DOUBLES at the 0.2 s
    // aim point (0.027 -> 0.056 m) and grows 50 % at 0.5 s, but at the 2 s
    // horizon it is SMALLER (1.62 -> 1.54 m), because a 200 deg turn has carried
    // the phase-led point back round the circle. The radius is unchanged by
    // construction: |v| is fixed and the heading rate is fixed, so v/w is too.
    float latSlipDeg = 0.f;      // max sideslip; 0 = off (the car model)
    float latKneeDps = 40.f;     // yaw rate at which beta reaches half of latSlipDeg

    // Scoring. Deliberately few terms: this project has already measured that
    // adding weights to a badly-posed problem does not fix it.
    float goalWeight   = 1.0f;   // alignment of the endpoint with the goal bearing
    float clearWeight  = 0.7f;   // how far along the primitive stays clear
    float smoothWeight = 0.25f;  // prefer low yaw rate, all else equal
    // COARSE FAR MAP -- AWARENESS ONLY, NEVER PERMISSION.
    //
    // The fine map decides what may be flown through: swept-volume clearance and
    // the confirmed-FREE speed budget both read it alone. The far map only says
    // which BEARING looks open beyond the fine map's honest range, and that is
    // added to the SCORE. A coarse cell is the size of the robot; it can tell you
    // there is a gap at 12 m, it cannot tell you the gap is free of a 0.3 m
    // trunk, and it must never be asked to.
    //
    // Marching stops at OCCUPIED only -- UNKNOWN does not block, because
    // unknown at range is the normal state and treating it as closed would make
    // this term a no-op.
    //
    // BUT UNKNOWN DOES NOT SCORE AS OPEN. It used to, and the result was that
    // the aircraft steered toward whatever it could not see -- which outdoors
    // is the sky. See `test/sky_open_check.cpp`. Openness is earned by a
    // confirmed distance; absence of a return is absence of knowledge.
    float farWeight  = 0.5f;
    // CLIMB IS NOT SYMMETRIC WITH DESCENT, and pricing it inside the goal term
    // treats it as though it were.
    //
    // Three reasons a forest aircraft should resist going up, none of which
    // apply equally to going down:
    //   * the map's honest marking range is 3.54 m and the camera sees +-28 deg
    //     vertically, so a climb flies into volume that was never observed;
    //   * the sky is unbounded, so any openness measure has an upward bias that
    //     no amount of filtering fully removes -- the fix above stops unknown
    //     scoring as open, but a genuine distant return above the canopy is
    //     still legitimately "open" and still the wrong place to go;
    //   * altitude is the one axis where the mission almost never wants motion.
    //     Under the canopy, up is not a route.
    //
    // Sized so that 15 deg of UNCOMMANDED climb costs 1.0 -- twice the most the
    // far term can offer at farWeight 0.5. Asymmetric on purpose: only positive
    // elevation is charged, and only above the commanded one. Descent is
    // dangerous for a different reason (the frustum's blind disc underneath)
    // and that is the near map's and the rangefinder's problem, not a scoring
    // weight's. 0 disables.
    float climbPenalty = 2.0f;
    // AND THE SAME ON DESCENT. The one-sided version was measured and it was
    // WRONG: suppressing climb does not remove the planner's appetite for
    // vertical motion, it INVERTS it. 5 seeds, forest, 400 steps --
    //
    //     climbPen  sinkPen   maxUP   maxDOWN   dist   travel  stopped
    //     0         0         0.44     0.10     153.6    61.8     184
    //     2         0         0.00     0.80     157.0    56.2     203
    //     6         0         0.00     0.77     158.6    55.6     206
    //     2         2         0.00     0.04     148.0    69.2     155
    //
    // One-sided traded a 0.44 m climb for a 0.80 m SINK -- eight times the
    // descent, and downward is the worse direction: the blind disc is below
    // (radius ~2x altitude) and so is the ground. Symmetric holds altitude to
    // 4 cm AND wins every other column: furthest progress, most distance
    // travelled, fewest stopped steps, same clearance.
    //
    // Also note 6 buys nothing over 2. The 6 was tuned against a synthetic unit
    // test with farWeight at twice its real value; in the loop it is inert.
    float descentPenalty = 2.0f;
    float farRangeM  = 20.f;   // proven value; do not move it and a level in the same test
    // HOW OPENNESS IS MEASURED ALONG A BEARING.
    //
    // FIRST_BLOCKED: distance to the first cell any level calls OCCUPIED. This
    // is what shipped, and it only worked because 2 m cells are BLIND to
    // individual trunks -- it was a proxy for density, not a measure of it.
    // Adding a 1 m rung broke it outright: in a forest every bearing has a trunk
    // within 7 m, so a finer first-blocker returns the same small number in every
    // direction, the term goes flat and stops discriminating (measured: 3-level
    // 0.666 against 0.670 with no ladder at all).
    //
    // DENSITY: fraction of sampled cells along the bearing that are OCCUPIED.
    // Immune to any single cell, so resolution stops being load-bearing and the
    // level count stops mattering. Same shape as a depth-image supervisor that
    // thresholds on the FRACTION of pixels nearer than d_min rather than on the
    // nearest one.
    enum class FarMode { FIRST_BLOCKED, DENSITY };
    FarMode farMode = FarMode::DENSITY;
};

class TrajectoryPlanner {
public:
    explicit TrajectoryPlanner(const TrajParams& p = TrajParams());
    const TrajParams& params() const { return p_; }

    // Same signature and same return type as GeneralPlanner::plan, so the two
    // can be swapped behind one flag and compared on identical worlds. The
    // extra argument is the vehicle's current heading, which a body-frame
    // library needs and a world-frame histogram did not.
    // One rung of the coarse ladder: a map and the range out to which its cells
    // are honest. Ordered FINE FIRST.
    struct CoarseLevel { const VoxelMap* map; float rangeM; };

    // THE FAR FIELD, as bearings rather than as cubes. Same job as `coarse` --
    // it scores a direction and can neither veto nor add speed -- but it keeps
    // the sensor's angular resolution instead of a cube's, which for awareness
    // is the only thing that matters. When set it REPLACES `coarse`.
    struct FarBearings { const BearingField* field; float rangeM; };

    // `coarse` is the OPTIONAL awareness ladder. It influences scoring only;
    // every safety test in plan() reads `m` alone. Empty disables it.
    //
    // Marching queries the FINEST level whose honest range still covers the
    // current distance, so a 0.25 m fine map does not hand straight over to 2 m
    // cells -- an 8x jump in one step, which throws away everything a
    // mid-resolution level could have told you between 3.5 m and 14 m.
    GeneralResult plan(const VoxelMap& m, float px, float py, float pz,
                       float curYawDeg, float goalAzDeg, float goalElDeg,
                       const std::vector<CoarseLevel>& coarse = {},
                       const FarBearings* far = nullptr);

    // The winning rollout in WORLD coordinates, for drawing. Empty if blocked.
    const std::vector<std::array<float, 3>>& chosen() const { return chosen_; }
    // Every admissible candidate, world frame -- this is the picture that makes
    // a bad decision obvious, because you can see what it rejected.
    const std::vector<std::vector<std::array<float, 3>>>& candidates() const {
        return cands_;
    }
    size_t librarySize() const { return prims_.size(); }

    // WHY nothing was admissible. "0 admissible" is a fact; this is the reason,
    // and they are different questions with different fixes. Rejected at the
    // very first rollout point means the aircraft is already boxed in; rejected
    // later means it simply cannot go far enough to earn any speed.
    // PER-PRIMITIVE EVALUATION, recorded during plan() rather than recomputed.
    //
    // plan() returns only the winner, which is all a classical controller needs.
    // A learned policy that RANKS primitives needs the losers too -- and it must
    // see them through the same rollout, the same sphereClear and the same
    // unknown rule the classical planner used, or the comparison between them
    // is not a comparison. So this is a recording of that loop, not a second
    // implementation of it.
    struct PrimEval {
        float freeM   = 0.f;    // CONFIRMED-FREE length; unknown earns nothing
        float endAz   = 0.f, endEl = 0.f;
        float goalErr = 0.f;    // normalised endpoint-vs-goal error
        float clear   = 0.f;    // freeM / (vMax * horizonS)
        float farOpen = 0.f;    // advisory only, never a veto
        float speed = 0.f, yawRate = 0.f, climb = 0.f;
        bool  admissible = false;
        int   why = 0;          // 0 admissible, 1 occupied, 2 unknown
    };
    const std::vector<PrimEval>& evals() const { return evals_; }
    // The body-frame displacement one dt along primitive `i`.
    //
    // THIS IS WHAT AN ENV MUST FLY, not the primitive's nominal speed. The
    // rollout sphereClear approved was integrated with the vehicle's own
    // first-order velocity lag (tau), so a caller that instead applies the
    // commanded speed directly moves further than the path that was checked --
    // and then collides on a primitive the veto had passed. Measured: the
    // classical score baseline collided on 3 of 3 maze seeds that way.
    void primFirstStep(size_t i, float& bx, float& by, float& bz) const {
        if (i >= prims_.size() || prims_[i].pts.empty()) { bx = by = bz = 0.f; return; }
        bx = prims_[i].pts[0][0]; by = prims_[i].pts[0][1]; bz = prims_[i].pts[0][2];
    }

    // The command a given primitive would issue, so a caller that selects by
    // index can fly it without going back through plan()'s argmax.
    void primCommand(size_t i, float& speed, float& yawRate, float& climb) const {
        if (i >= prims_.size()) { speed = yawRate = climb = 0.f; return; }
        speed = prims_[i].speed; yawRate = prims_[i].yawRate; climb = prims_[i].climb;
    }

    struct Reject {
        int occupied = 0;   // an OCCUPIED cell inside the robot ball
        int unknown  = 0;   // the centreline was not confirmed FREE
        int tooShort = 0;   // cleared some distance, but under minFreeM
        int atStart  = 0;   // of those, rejected on the FIRST rollout point
    };
    const Reject& lastReject() const { return reject_; }

private:
    struct Prim {
        std::vector<std::array<float, 3>> pts;  // body frame, +y forward
        float speed = 0, yawRate = 0, climb = 0;
    };
    TrajParams p_;
    std::vector<Prim> prims_;
    std::vector<std::array<float, 3>> chosen_;
    std::vector<std::vector<std::array<float, 3>>> cands_;
    float lastAz_ = 0, lastEl_ = 0;
    bool  haveLast_ = false;
    Reject reject_;
    std::vector<PrimEval> evals_;
};

}  // namespace sim
